apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: sgy-nvidia-gpu-device-plugin
  name: sgy-nvidia-gpu-device-plugin-small-cos
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: sgy-nvidia-gpu-device-plugin
  template:
    metadata:
      annotations:
        components.gke.io/component-name: gpu-device-plugin
        components.gke.io/component-version: 1.32.2-gke.0
      labels:
        k8s-app: sgy-nvidia-gpu-device-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
              - key: gke-no-default-nvidia-gpu-device-plugin
                operator: NotIn
                values:
                - "true"
              - key: cloud.google.com/gke-cpu-scaling-level
                operator: Lt
                values:
                - "16"
              - key: cloud.google.com/gke-os-distribution
                operator: In
                values:
                - cos
      serviceAccountName: gpu-device-plugin
      containers:
      - command:
        - /usr/bin/nvidia-gpu-device-plugin
        - -logtostderr
        - --enable-container-gpu-metrics
        - --enable-health-monitoring
        env:
        - name: XID_CONFIG
          valueFrom:
            configMapKeyRef:
              key: HealthCriticalXid
              name: xid-config
              optional: true
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: GOMAXPROCS
          value: "1"
        image: us-west1-docker.pkg.dev/yshangguan-gke-dev/sgy-test-image/nvidia-gpu-device-plugin@sha256:8169f0453f47e156d8f921052c2f850d40ed89a4c7f56231905d141faaeae0a7
        imagePullPolicy: IfNotPresent
        name: nvidia-gpu-device-plugin
        ports:
        - containerPort: 2112
          name: prometheus
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /device-plugin
          name: device-plugin
        - mountPath: /dev
          name: dev
        - mountPath: /usr/local
          name: kubernetes-bin
        - mountPath: /var/lib/kubelet/pod-resources
          name: pod-resources
        - mountPath: /proc
          name: proc
        - mountPath: /etc/nvidia
          name: nvidia-config
        - mountPath: /opt
          name: opt
        - mountPath: /tmp/nvidia-mps
          name: mps
      - env:
        - name: GOMAXPROCS
          value: "2"
        - name: COLLECTOR_CONFIG_PATH
          value: /conf/nvidia-metrics-collector-config-data.textproto
        - name: SPLIT_GAUGE_BUFFER
          value: "true"
        - name: PROJECT_NUMBER
          value: "744139846045"
        - name: LOCATION
          value: us-central1-c
        - name: CLUSTER_NAME
          value: weitong-cluster
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CONTAINER_NAME
          value: nvidia-metrics-collector
        - name: COMPONENT_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['components.gke.io/component-version']
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['components.gke.io/component-name']
        image: us-central1-artifactregistry.gcr.io/gke-release/gke-release/gke-metrics-collector:20250519_2300_RC0@sha256:8eb5ca83cc3da9605c38ff5a839a9eb4123434ca631d715193bbdc8262bc3497
        imagePullPolicy: IfNotPresent
        name: nvidia-metrics-collector
        resources:
          limits:
            cpu: "1"
            memory: 30Mi
          requests:
            cpu: 5m
            memory: 30Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: nvidia-metrics-collector-config-map-vol
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - bash
        - -c
        - |
          LABELS=$( curl --retry 5 -H "Metadata-Flavor:Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/kube-labels || exit 1 )
          IFS=,; for label in $LABELS; do
            IFS==; read -r LABEL VALUE <<< "$label"
            if [[ "${LABEL}" == "cloud.google.com/gke-gpu-driver-version" ]]; then
              GPU_DRIVER_VERSION=$VALUE
            fi
          done
          if [[ "${GPU_DRIVER_VERSION}" == "latest" ]]; then
            echo "latest" > /etc/nvidia/gpu_driver_version_config.txt
            /cos-gpu-installer install --version=latest || exit 1
          elif [[ "${GPU_DRIVER_VERSION}" == "default" ]]; then
            echo "default" > /etc/nvidia/gpu_driver_version_config.txt
            /cos-gpu-installer install || exit 1
          else
            echo "disabled" > /etc/nvidia/gpu_driver_version_config.txt
            echo "GPU driver auto installation is disabled."
          fi
          echo "Waiting for GPU driver libraries to be available."
          while ! [[ -f /usr/local/nvidia/lib64/libcuda.so ]]; do
            sleep 5
          done
          echo "GPU driver is installed."
          echo "InitContainer succeeded. Start nvidia-gpu-device-plugin container."
          exit 0
        env:
        - name: NVIDIA_INSTALL_DIR_HOST
          value: /home/kubernetes/bin/nvidia
        - name: NVIDIA_INSTALL_DIR_CONTAINER
          value: /usr/local/nvidia
        - name: VULKAN_ICD_DIR_HOST
          value: /home/kubernetes/bin/nvidia/vulkan/icd.d
        - name: VULKAN_ICD_DIR_CONTAINER
          value: /etc/vulkan/icd.d
        - name: ROOT_MOUNT_DIR
          value: /root
        - name: COS_TOOLS_DIR_HOST
          value: /var/lib/cos-tools
        - name: COS_TOOLS_DIR_CONTAINER
          value: /build/cos-tools
        image: cos-nvidia-installer:fixed
        imagePullPolicy: Never
        name: nvidia-driver-installer
        resources:
          requests:
            cpu: 150m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local
          name: kubernetes-bin
        - mountPath: /dev
          name: dev
        - mountPath: /root
          name: root-mount
        - mountPath: /build/cos-tools
          name: cos-tools
        - mountPath: /etc/nvidia
          name: nvidia-config
        - mountPath: /etc/vulkan/icd.d
          name: vulkan-icd-mount
      - command:
        - bash
        - -c
        - |
          GPU_DRIVER_VERSION=$( cat /etc/nvidia/gpu_driver_version_config.txt )
          if [ "${GPU_DRIVER_VERSION}" = "disabled" ]; then
            exit 0
          else
            /usr/bin/gpu_partitioner -logtostderr
          fi
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        image: us-central1-artifactregistry.gcr.io/gke-release/gke-release/nvidia-partition-gpu:1.32.4-gke.6@sha256:7ef573f6c76f891e4d9f835c7a1f0cbf1d9a2537b6e8c4a8449126c581784906
        imagePullPolicy: IfNotPresent
        name: partition-gpus
        resources:
          requests:
            cpu: 150m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local
          name: kubernetes-bin
        - mountPath: /dev
          name: dev
        - mountPath: /etc/nvidia
          name: nvidia-config
        - mountPath: /opt
          name: opt
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: components.gke.io/gke-managed-components
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
        name: device-plugin
      - hostPath:
          path: /dev
          type: Directory
        name: dev
      - hostPath:
          path: /var/lib/kubelet/pod-resources
          type: Directory
        name: pod-resources
      - hostPath:
          path: /proc
          type: Directory
        name: proc
      - hostPath:
          path: /etc/nvidia
          type: DirectoryOrCreate
        name: nvidia-config
      - hostPath:
          path: /tmp/nvidia-mps
          type: DirectoryOrCreate
        name: mps
      - hostPath:
          path: /home/kubernetes/bin
          type: Directory
        name: kubernetes-bin
      - hostPath:
          path: /
          type: Directory
        name: root-mount
      - hostPath:
          path: /opt
          type: Directory
        name: opt
      - configMap:
          defaultMode: 420
          items:
          - key: gpu-device-plugin-metrics-collector-config-data
            path: nvidia-metrics-collector-config-data.textproto
          name: nvidia-metrics-collector-config-map
        name: nvidia-metrics-collector-config-map-vol
      - hostPath:
          path: /var/lib/cos-tools
          type: DirectoryOrCreate
        name: cos-tools
      - hostPath:
          path: /home/kubernetes/bin/nvidia/vulkan/icd.d
          type: DirectoryOrCreate
        name: vulkan-icd-mount
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
